### ISSUE TITLE
Finalize hosting

### ISSUE THREAD

**Issue by decompil3d** [DevProgress/debate-bingo#17]
Right now, bingo is hosted on a free Heroku instance. We need to move it to a proper one.
- [ ] DNS transfered to CloudFlare
- [ ] CloudFlare does SSL termination + Http proxy for the site. Backend is GH-pages.
- [x] Static content dumped onto GH-pages.
- [ ] Do some work to ensure CloudFlare caches the html and js assets of github.
- [ ] Turn down heroku and squarespace. They will be completely obsoleted.

**Comment by dglazkov** [comment]
Move to gh-pages + cloudflare.

**Comment by nellshamrell** [comment]
Here is what I currently see:

Things that can be worked on now
- [x] A Github pages page must be set up for this project 

Decisions that I see need to be made before we can move too far forward with this
- [x] DNS must be purchased
- [ ] When the DNS is purchased, the DevProgress account with Cloudflare must have this site added to it

Things to be done once our Cloudflare and Github pages sites are set up:
- [ ] Cloudflare must also be set up to do SSL termination + HTTP proxy
- [ ] Cloudflare must also be set up to cache the html and js assets of the Github pages site

**Comment by decompil3d** [comment]
Sounds like we're finalizing on hosting on squarespace. So we need to deploy there and document the process.

**Comment by mayankdeore** [comment]
you Can try Free Trail hosting on Rackbank Datacenter 
https://www.rackbank.com/in/free-trial/

**Comment by dglazkov** [comment]
Done.
