### ISSUE TITLE
Swap out candidate photos on bingo overlay

### ISSUE THREAD

**Issue by decompil3d** [DevProgress/debate-bingo#28]
We need to use licensed photos. Unclear if the current ones are legit. @decause provided this info for finding legitimate replacement photos. Bonus points for pulling in multiple photos and showing a random one each time.

> The folks here at HQ have pointed me towards our official campaign Flickr, which includes photos that are Creative Commons licensed, be sure to check individual photos you download: https://www.flickr.com/photos/hillaryclinton/
> 
> As for the trump photos, you can use Google Image searching with an advanced search setting for "Licensed for reuse with modification" to find Create Commons Sourced images. Be sure to double check them, but here's the link I used: https://www.google.com/search?site=&tbm=isch&source=hp&biw=&bih=&q=Donald+Trump&btnG=Search+by+image#q=Donald+Trump&tbm=isch&tbs=sur:fmc
> 
> Hope this helps,
> --RemyD."

**Comment by dglazkov** [comment]
If peeps can pick out photos, I can do the swapping + attribution (if necessary).

**Comment by dglazkov** [comment]
https://www.flickr.com/photos/gageskidmore/5440002785 seems like one good possibility.

**Comment by decompil3d** [comment]
How's this for Hillary? https://www.flickr.com/photos/gageskidmore/24007578223
