### ISSUE TITLE
Implement free tile at center

### ISSUE THREAD

**Issue by decompil3d** [DevProgress/debate-bingo#3]

**Comment by kkschick** [comment]
@JonathanKeslin Is anyone working on this yet? If not, I can take it!

**Comment by decompil3d** [comment]
Nope - all yours. Shouldn't be too much work.

Look at `src/BingoCard.js`. You probably just need to add a 1 for the center tile in `EMPTY_BOARD` and then provide logic to set the image to show in the free tile (maybe a prop that gets passed down from `BingoCard` into the middle `BingoRow`, into the middle `BingoTile`. Up to you how hard-coded this should be -- not like this has to be super-generalizable). Also make sure that there's no button on that tile so it cannot be undaubed.

Let me know if you have questions. Hope my code isn't too messy ;)

**Comment by decompil3d** [comment]
Fixed with ea5a7b2
