### ISSUE TITLE
Pinterest needs a bigger image to share

### ISSUE THREAD

**Issue by bradyk** [DevProgress/debate-bingo#41]
Either remove the pinterest share button (my recommendation) or make sure there is an image that's big enough to share on pinterest.

Clicked on pinterest share button from the footer.
Pinterest pop up popped up fine.
Clicked to share, and got a error that the image was too small.
![screen shot 2016-09-22 at 9 41 13 pm](https://cloud.githubusercontent.com/assets/1565834/18774398/85e30e4e-810d-11e6-927c-61100db931a3.png)

**Comment by whereistanya** [comment]
I'll remove the button.

**Comment by whereistanya** [comment]
Or, actually, a screenshot of http://presidentialdebatebingo.com/ might be cool. That's a nice looking page. What do you think?

**Comment by jillh510** [comment]
If it's the same amount of work to add a screenshot as to remove a button, then I'd say go for it. But if it's more work, then not worth it.

**Comment by whereistanya** [comment]
The pinterest button isn't working reliably (for unrelated images on the web) so I'll yank it out completely rather than debugging.
