### ISSUE TITLE
Twitter share number missing

### ISSUE THREAD

**Issue by bradyk** [DevProgress/debate-bingo#42]
The number is missing below the twitter icon on the social share set on the bottom.

I even tweeted. :)

![screen shot 2016-09-22 at 10 06 18 pm](https://cloud.githubusercontent.com/assets/1565834/18774732/ef433262-8110-11e6-8c05-f566797fd0bc.png)

**Comment by whereistanya** [comment]
Twitter doesn't have a count API any more. We'd have to store them ourselves. 

https://www.npmjs.com/package/react-share#23112015

**Comment by jillh510** [comment]
Can we close this as "cannot fix"?
