### ISSUE TITLE
Completed card images are too big.

### ISSUE THREAD

**Issue by bradyk** [DevProgress/debate-bingo#43]
The images of the candidates that appear when you get bingo are too big. 
They:
- Load slowly
- Don't resize (on 11'' air)
- Don't scroll.

Images should be sized down or replaced.

![screen shot 2016-09-22 at 10 07 43 pm](https://cloud.githubusercontent.com/assets/1565834/18774750/193035c0-8111-11e6-8a0f-cd323eee0f1c.png)

**Comment by bradyk** [comment]
Looks like image changes size when you resize the window width.

**Comment by whereistanya** [comment]
I think this is good now. Reopen if not.
