### ISSUE TITLE
"Back" button works strangely on Android

### ISSUE THREAD

**Issue by jillh510** [DevProgress/debate-bingo#46]
If I go to the site on my Android phone, touch a candidate name to get a Bingo card, then touch the "back" button, I'm taken out of the browser and back to the home screen. I realize this is because we're a single-page app, but can we push a URL to history so that the back button works?

**Comment by dglazkov** [comment]
We will need to use better routing here. Since it's a single-page-app (aka SPA), it needs to use `history.pushState` to simulate navigation from home page to bingo tiles page and back.

**Comment by dglazkov** [comment]
Here's a nice tutorial to follow along: http://jamesknelson.com/routing-with-raw-react/
