### ISSUE TITLE
After bingo, free square turns into a button

### ISSUE THREAD

**Issue by decompil3d** [DevProgress/debate-bingo#7]
Get a bingo that includes the center free square. The free space turns into a button instead of staying a free space

**Comment by kkschick** [comment]
I wasn't able to reproduce this—can you take a look at my branch and verify this is working for you now?

**Comment by decompil3d** [comment]
Hey Katie,

I'm not at a machine that I can test your branch on right now, but I see
that this repros in master (https://debate-bingo-dev.herokuapp.com) when
doing a top-left to bottom-right diagonal bingo.

--Jonathan

**Comment by kkschick** [comment]
Ah, I see. Yep, this should be fixed now on my branch.

**Comment by decompil3d** [comment]
Still repros after commit 23f440f (your last pr). Can you take another look?
