### ISSUE TITLE
UI Defect: There's a gap between white bar and top of screen on mobile view. 

### ISSUE THREAD

**Issue by sharkswithbraces** [DevProgress/debate-bingo#88]
Gap only occurs up to 640 width. I believe this is messing things up:

@media only screen and (max-width: 640px)
.sqs-layout .sqs-row .sqs-block:first-child {
   padding-top: 14px !important;
}

Can we make it 0px or try to remove this?

**Comment by jillh510** [comment]
Should be fixed with PR 87

**Comment by jillh510** [comment]
Will this be fixed with the move to gh-pages?
